# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1305, 683)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(61, 61, 61);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BTN_PLAY = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_PLAY.setGeometry(QtCore.QRect(940, 10, 121, 61))
        self.BTN_PLAY.setMouseTracking(False)
        self.BTN_PLAY.setAutoFillBackground(False)
        self.BTN_PLAY.setStyleSheet("background-color:rgb(85, 170, 127);")
        self.BTN_PLAY.setObjectName("BTN_PLAY")
        self.BTN_PAUSE = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_PAUSE.setGeometry(QtCore.QRect(1080, 10, 121, 61))
        self.BTN_PAUSE.setAutoFillBackground(False)
        self.BTN_PAUSE.setStyleSheet("background-color:rgb(85, 170, 127);")
        self.BTN_PAUSE.setObjectName("BTN_PAUSE")
        self.BTN_OPEN = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_OPEN.setGeometry(QtCore.QRect(1080, 100, 121, 61))
        self.BTN_OPEN.setAutoFillBackground(False)
        self.BTN_OPEN.setStyleSheet("background-color:rgb(85, 170, 127);")
        self.BTN_OPEN.setObjectName("BTN_OPEN")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 911, 541))
        self.frame.setStyleSheet("background-color:rgb(139, 139, 139);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(4)
        self.frame.setMidLineWidth(4)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(1, -6, 911, 551))
        self.label.setText("")
        self.label.setObjectName("label")
        self.BTN_RESTART = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_RESTART.setGeometry(QtCore.QRect(940, 100, 121, 61))
        self.BTN_RESTART.setAutoFillBackground(False)
        self.BTN_RESTART.setStyleSheet("background-color:rgb(85, 170, 127);")
        self.BTN_RESTART.setObjectName("BTN_RESTART")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(920, -20, 21, 801))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(1300, -20, 20, 811))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(-140, 560, 1071, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.progressBar = QtWidgets.QSlider(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 580, 901, 20))
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.progress_num = QtWidgets.QLabel(self.centralwidget)
        self.progress_num.setGeometry(QtCore.QRect(450, 600, 54, 18))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.progress_num.setPalette(palette)
        self.progress_num.setObjectName("progress_num")
        self.BTN_Tools = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_Tools.setGeometry(QtCore.QRect(1220, 10, 81, 151))
        self.BTN_Tools.setStyleSheet("background:rgb(0, 85, 255)")
        self.BTN_Tools.setObjectName("BTN_Tools")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(1050, 510, 161, 131))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_map = QtWidgets.QLabel(self.frame_2)
        self.label_map.setGeometry(QtCore.QRect(3, 7, 151, 121))
        self.label_map.setText("")
        self.label_map.setObjectName("label_map")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(930, 500, 381, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Slider1 = QtWidgets.QSlider(self.centralwidget)
        self.Slider1.setGeometry(QtCore.QRect(950, 360, 341, 20))
        self.Slider1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider1.setObjectName("Slider1")
        self.Slider2 = QtWidgets.QSlider(self.centralwidget)
        self.Slider2.setGeometry(QtCore.QRect(950, 430, 341, 20))
        self.Slider2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider2.setObjectName("Slider2")
        self.comboBox_optimize = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_optimize.setGeometry(QtCore.QRect(1080, 320, 72, 26))
        self.comboBox_optimize.setObjectName("comboBox_optimize")
        self.label_threshold1 = QtWidgets.QLabel(self.centralwidget)
        self.label_threshold1.setGeometry(QtCore.QRect(1093, 380, 61, 20))
        self.label_threshold1.setObjectName("label_threshold1")
        self.label_threshold2 = QtWidgets.QLabel(self.centralwidget)
        self.label_threshold2.setGeometry(QtCore.QRect(1090, 450, 61, 20))
        self.label_threshold2.setObjectName("label_threshold2")
        self.BTN_test = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_test.setGeometry(QtCore.QRect(1090, 190, 80, 26))
        self.BTN_test.setObjectName("BTN_test")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1305, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BTN_PLAY.setText(_translate("MainWindow", "Play"))
        self.BTN_PAUSE.setText(_translate("MainWindow", "Pause"))
        self.BTN_OPEN.setText(_translate("MainWindow", "Open"))
        self.BTN_RESTART.setText(_translate("MainWindow", "Restart"))
        self.progress_num.setText(_translate("MainWindow", "0.0%"))
        self.BTN_Tools.setText(_translate("MainWindow", "Tools"))
        self.label_threshold1.setText(_translate("MainWindow", "0"))
        self.label_threshold2.setText(_translate("MainWindow", "0"))
        self.BTN_test.setText(_translate("MainWindow", "test"))


