# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_For_Processor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1253, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 161, 581))
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "文件列表")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(150, 0, 20, 581))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(970, 0, 281, 571))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.BTN_Open = QtWidgets.QPushButton(self.frame_2)
        self.BTN_Open.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.BTN_Open.setStyleSheet("background-color:rgb(155, 195, 255)")
        self.BTN_Open.setObjectName("BTN_Open")
        self.lbl_img1 = QtWidgets.QLabel(self.frame_2)
        self.lbl_img1.setGeometry(QtCore.QRect(20, 130, 101, 101))
        self.lbl_img1.setAutoFillBackground(False)
        self.lbl_img1.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_img1.setText("")
        self.lbl_img1.setObjectName("lbl_img1")
        self.BTN_Undo1 = QtWidgets.QPushButton(self.frame_2)
        self.BTN_Undo1.setGeometry(QtCore.QRect(90, 230, 31, 21))
        self.BTN_Undo1.setObjectName("BTN_Undo1")
        self.BTN_Undo2 = QtWidgets.QPushButton(self.frame_2)
        self.BTN_Undo2.setGeometry(QtCore.QRect(220, 230, 41, 21))
        self.BTN_Undo2.setObjectName("BTN_Undo2")
        self.BTN_Undo = QtWidgets.QPushButton(self.frame_2)
        self.BTN_Undo.setGeometry(QtCore.QRect(100, 10, 71, 21))
        self.BTN_Undo.setStyleSheet("background-color:rgb(155, 195, 255)")
        self.BTN_Undo.setObjectName("BTN_Undo")
        self.BTN_Confirm = QtWidgets.QPushButton(self.frame_2)
        self.BTN_Confirm.setGeometry(QtCore.QRect(180, 10, 81, 21))
        self.BTN_Confirm.setStyleSheet("background-color:rgb(255, 123, 147)")
        self.BTN_Confirm.setObjectName("BTN_Confirm")
        self.RDO_Single = QtWidgets.QRadioButton(self.frame_2)
        self.RDO_Single.setGeometry(QtCore.QRect(10, 100, 71, 19))
        self.RDO_Single.setObjectName("RDO_Single")
        self.RDO_Pair = QtWidgets.QRadioButton(self.frame_2)
        self.RDO_Pair.setGeometry(QtCore.QRect(90, 100, 71, 19))
        self.RDO_Pair.setObjectName("RDO_Pair")
        self.lbl_img2 = QtWidgets.QLabel(self.frame_2)
        self.lbl_img2.setGeometry(QtCore.QRect(160, 130, 101, 101))
        self.lbl_img2.setAutoFillBackground(False)
        self.lbl_img2.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_img2.setText("")
        self.lbl_img2.setObjectName("lbl_img2")
        self.name1 = QtWidgets.QLabel(self.frame_2)
        self.name1.setGeometry(QtCore.QRect(30, 230, 61, 21))
        self.name1.setText("")
        self.name1.setObjectName("name1")
        self.name2 = QtWidgets.QLabel(self.frame_2)
        self.name2.setGeometry(QtCore.QRect(160, 230, 61, 21))
        self.name2.setText("")
        self.name2.setObjectName("name2")
        self.ComboxBox_Label = QtWidgets.QComboBox(self.frame_2)
        self.ComboxBox_Label.setGeometry(QtCore.QRect(90, 540, 87, 22))
        self.ComboxBox_Label.setObjectName("ComboxBox_Label")
        self.annotation1 = QtWidgets.QLabel(self.frame_2)
        self.annotation1.setGeometry(QtCore.QRect(20, 540, 61, 21))
        self.annotation1.setObjectName("annotation1")
        self.BTN_Pre = QtWidgets.QPushButton(self.frame_2)
        self.BTN_Pre.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.BTN_Pre.setStyleSheet("background-color:rgb(241, 241, 0)")
        self.BTN_Pre.setObjectName("BTN_Pre")
        self.BTN_Next = QtWidgets.QPushButton(self.frame_2)
        self.BTN_Next.setGeometry(QtCore.QRect(100, 40, 71, 21))
        self.BTN_Next.setStyleSheet("background-color:rgb(241, 241, 0)")
        self.BTN_Next.setObjectName("BTN_Next")
        self.RDO_View = QtWidgets.QRadioButton(self.frame_2)
        self.RDO_View.setGeometry(QtCore.QRect(190, 40, 61, 19))
        self.RDO_View.setObjectName("RDO_View")
        self.BTN_Save = QtWidgets.QPushButton(self.frame_2)
        self.BTN_Save.setGeometry(QtCore.QRect(150, 70, 81, 21))
        self.BTN_Save.setStyleSheet("background-color:rgb(255, 123, 147)")
        self.BTN_Save.setObjectName("BTN_Save")
        self.BTN_Delete = QtWidgets.QPushButton(self.frame_2)
        self.BTN_Delete.setGeometry(QtCore.QRect(40, 70, 81, 21))
        self.BTN_Delete.setStyleSheet("background-color:rgb(255, 123, 147)")
        self.BTN_Delete.setObjectName("BTN_Delete")
        self.display_area = QtWidgets.QScrollArea(self.centralwidget)
        self.display_area.setGeometry(QtCore.QRect(169, 6, 791, 571))
        self.display_area.setWidgetResizable(True)
        self.display_area.setObjectName("display_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 789, 569))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.display_area.setWidget(self.scrollAreaWidgetContents)
        self.frame_2.raise_()
        self.treeWidget.raise_()
        self.line.raise_()
        self.display_area.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1253, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ImageLabeler"))
        self.BTN_Open.setText(_translate("MainWindow", "Open"))
        self.BTN_Undo1.setText(_translate("MainWindow", "U1"))
        self.BTN_Undo2.setText(_translate("MainWindow", "U2"))
        self.BTN_Undo.setText(_translate("MainWindow", "ShutOpen"))
        self.BTN_Confirm.setText(_translate("MainWindow", "Confirm"))
        self.RDO_Single.setText(_translate("MainWindow", "Single"))
        self.RDO_Pair.setText(_translate("MainWindow", "Pair"))
        self.annotation1.setText(_translate("MainWindow", "Labels:"))
        self.BTN_Pre.setText(_translate("MainWindow", "Pre"))
        self.BTN_Next.setText(_translate("MainWindow", "Next"))
        self.RDO_View.setText(_translate("MainWindow", "View"))
        self.BTN_Save.setText(_translate("MainWindow", "Save"))
        self.BTN_Delete.setText(_translate("MainWindow", "Delete"))

