# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_For_Processor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1147, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(160, 440, 991, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.BTN_Open = QtWidgets.QPushButton(self.frame)
        self.BTN_Open.setGeometry(QtCore.QRect(20, 10, 93, 41))
        self.BTN_Open.setStyleSheet("background-color:rgb(158, 192, 255)")
        self.BTN_Open.setObjectName("BTN_Open")
        self.BTN_Save = QtWidgets.QPushButton(self.frame)
        self.BTN_Save.setGeometry(QtCore.QRect(20, 70, 91, 41))
        self.BTN_Save.setStyleSheet("background-color:rgb(255, 105, 133)")
        self.BTN_Save.setObjectName("BTN_Save")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(383, 0, 20, 111))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Slider_Min = QtWidgets.QSlider(self.frame)
        self.Slider_Min.setGeometry(QtCore.QRect(470, 20, 451, 22))
        self.Slider_Min.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Min.setObjectName("Slider_Min")
        self.Slider_Max = QtWidgets.QSlider(self.frame)
        self.Slider_Max.setGeometry(QtCore.QRect(470, 70, 451, 22))
        self.Slider_Max.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Max.setObjectName("Slider_Max")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(430, 60, 31, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(430, 10, 31, 41))
        self.label_2.setObjectName("label_2")
        self.lbl_Min = QtWidgets.QLabel(self.frame)
        self.lbl_Min.setGeometry(QtCore.QRect(930, 20, 51, 20))
        self.lbl_Min.setObjectName("lbl_Min")
        self.lbl_Max = QtWidgets.QLabel(self.frame)
        self.lbl_Max.setGeometry(QtCore.QRect(930, 70, 51, 20))
        self.lbl_Max.setObjectName("lbl_Max")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(230, 0, 16, 111))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(280, 10, 71, 21))
        self.label_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_7.setObjectName("label_7")
        self.ComboBox = QtWidgets.QComboBox(self.frame)
        self.ComboBox.setGeometry(QtCore.QRect(260, 40, 111, 31))
        self.ComboBox.setObjectName("ComboBox")
        self.ComboBox.addItem("")
        self.ComboBox.addItem("")
        self.BTN_ShutOpen = QtWidgets.QPushButton(self.frame)
        self.BTN_ShutOpen.setGeometry(QtCore.QRect(130, 10, 93, 41))
        self.BTN_ShutOpen.setStyleSheet("background-color:rgb(158, 192, 255)")
        self.BTN_ShutOpen.setObjectName("BTN_ShutOpen")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(169, 0, 981, 431))
        self.frame_2.setStyleSheet("background-color:rgb(200, 200, 200)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(470, 0, 41, 641))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lbl_ProcessedImage = QtWidgets.QLabel(self.frame_2)
        self.lbl_ProcessedImage.setEnabled(True)
        self.lbl_ProcessedImage.setGeometry(QtCore.QRect(570, 60, 301, 301))
        self.lbl_ProcessedImage.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_ProcessedImage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_ProcessedImage.setText("")
        self.lbl_ProcessedImage.setObjectName("lbl_ProcessedImage")
        self.lbl_RawImage = QtWidgets.QLabel(self.frame_2)
        self.lbl_RawImage.setEnabled(True)
        self.lbl_RawImage.setGeometry(QtCore.QRect(100, 60, 301, 301))
        self.lbl_RawImage.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_RawImage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_RawImage.setText("")
        self.lbl_RawImage.setObjectName("lbl_RawImage")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 1, 171, 551))
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1147, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BTN_Open.setText(_translate("MainWindow", "Open"))
        self.BTN_Save.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Max:"))
        self.label_2.setText(_translate("MainWindow", "Min:"))
        self.lbl_Min.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_Max.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "约束条件"))
        self.ComboBox.setItemText(0, _translate("MainWindow", "像素值"))
        self.ComboBox.setItemText(1, _translate("MainWindow", "梯度"))
        self.BTN_ShutOpen.setText(_translate("MainWindow", "ShutOpen"))

